import {
  ConfigPlugin,
  IOSConfig,
  withAppDelegate,
  withDangerousMod,
  withXcodeProject,
} from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';

import { TrustPinPluginError, TrustPinPluginProps, usesInlineCredentials } from './types';

export const PLIST_FILE_NAME = 'TrustPin-Info.plist';

/** Builds the plist the native `fromPlist` loader reads. */
export function buildPlist(props: TrustPinPluginProps): string {
  const entries: [string, string][] = [
    ['OrganizationId', props.organizationId!],
    ['ProjectId', props.projectId!],
    ['PublicKey', props.publicKey!],
  ];
  if (props.mode) {
    entries.push(['Mode', props.mode]);
  }
  if (props.configurationUrl) {
    entries.push(['ConfigurationURL', props.configurationUrl]);
  }
  if (props.embeddedConfigurationFile) {
    // The native loader resolves this as a resource name in the same bundle,
    // so only the file name travels into the plist.
    entries.push(['EmbeddedConfigurationFile', path.basename(props.embeddedConfigurationFile)]);
  }

  const body = entries
    .map(([key, value]) => `\t<key>${key}</key>\n\t<string>${escapeXml(value)}</string>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by the @trustpin/react-native config plugin. Do not edit. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
${body}
</dict>
</plist>
`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Inserts the native init call as the first statement of
 * `didFinishLaunchingWithOptions`, so pinning is active before React Native
 * builds anything. Idempotent: re-running prebuild does not stack calls.
 */
export function addStartCall(contents: string, logLevel?: string): string {
  if (contents.includes('TrustPinReactNative.start(')) {
    return contents;
  }

  const call = logLevel
    ? `TrustPinReactNative.start(logLevel: .${logLevel})`
    : 'TrustPinReactNative.start()';

  const withImport = contents.includes('import TrustPinReactNative')
    ? contents
    : contents.replace(/(^import [^\n]+\n)(?![\s\S]*^import )/m, `$1import TrustPinReactNative\n`);

  const launchSignature = /(func application\([\s\S]*?didFinishLaunchingWithOptions[\s\S]*?\) -> Bool \{\n)/;
  if (!launchSignature.test(withImport)) {
    throw new TrustPinPluginError(
      'could not find application(_:didFinishLaunchingWithOptions:) in AppDelegate.swift. ' +
        `Add "${call}" as its first statement manually.`,
    );
  }

  return withImport.replace(
    launchSignature,
    `$1    // Pinning starts before React Native is created; JavaScript cannot alter it.\n    ${call}\n\n`,
  );
}

const withTrustPinPlist: ConfigPlugin<TrustPinPluginProps> = (config, props) =>
  withDangerousMod(config, [
    'ios',
    async modConfig => {
      const projectRoot = modConfig.modRequest.projectRoot;
      const platformRoot = modConfig.modRequest.platformProjectRoot;
      const appName = IOSConfig.XcodeUtils.getProjectName(projectRoot);
      const destination = path.join(platformRoot, appName, PLIST_FILE_NAME);

      const contents = usesInlineCredentials(props)
        ? buildPlist(props)
        : readUserConfigFile(projectRoot, props.ios!.configFile!);

      fs.mkdirSync(path.dirname(destination), { recursive: true });
      fs.writeFileSync(destination, contents);
      return modConfig;
    },
  ]);

/**
 * Copies the embedded configuration next to the plist. Writing the file is
 * only half the job: `withEmbeddedSeedInBundle` adds it to the app target so
 * the native loader can resolve it at runtime.
 */
const withEmbeddedSeed: ConfigPlugin<TrustPinPluginProps> = (config, props) =>
  withDangerousMod(config, [
    'ios',
    async modConfig => {
      if (!props.embeddedConfigurationFile) {
        return modConfig;
      }
      const projectRoot = modConfig.modRequest.projectRoot;
      const platformRoot = modConfig.modRequest.platformProjectRoot;
      const appName = IOSConfig.XcodeUtils.getProjectName(projectRoot);
      const source = path.resolve(projectRoot, props.embeddedConfigurationFile);
      if (!fs.existsSync(source)) {
        throw new TrustPinPluginError(`embeddedConfigurationFile not found: ${source}`);
      }
      const destination = path.join(platformRoot, appName, path.basename(source));
      fs.mkdirSync(path.dirname(destination), { recursive: true });
      fs.copyFileSync(source, destination);
      return modConfig;
    },
  ]);

const withEmbeddedSeedInBundle: ConfigPlugin<TrustPinPluginProps> = (config, props) =>
  withXcodeProject(config, modConfig => {
    if (!props.embeddedConfigurationFile) {
      return modConfig;
    }
    const project = modConfig.modResults;
    const projectName = IOSConfig.XcodeUtils.getProjectName(modConfig.modRequest.projectRoot);
    const filePath = `${projectName}/${path.basename(props.embeddedConfigurationFile)}`;

    if (!project.hasFile(filePath)) {
      IOSConfig.XcodeUtils.addResourceFileToGroup({
        filepath: filePath,
        groupName: projectName,
        project,
        isBuildFile: true,
        verbose: false,
      });
    }
    return modConfig;
  });

function readUserConfigFile(projectRoot: string, configFile: string): string {
  const source = path.resolve(projectRoot, configFile);
  if (!fs.existsSync(source)) {
    throw new TrustPinPluginError(`configFile not found: ${source}`);
  }
  return fs.readFileSync(source, 'utf8');
}

/**
 * The native loader reads the plist from the app bundle, so writing the file
 * is not enough — it has to be a resource of the app target.
 */
const withPlistInBundle: ConfigPlugin = config =>
  withXcodeProject(config, modConfig => {
    const project = modConfig.modResults;
    const projectName = IOSConfig.XcodeUtils.getProjectName(modConfig.modRequest.projectRoot);
    const filePath = `${projectName}/${PLIST_FILE_NAME}`;

    if (!project.hasFile(filePath)) {
      IOSConfig.XcodeUtils.addResourceFileToGroup({
        filepath: filePath,
        groupName: projectName,
        project,
        isBuildFile: true,
        verbose: false,
      });
    }
    return modConfig;
  });

const withInitCall: ConfigPlugin<TrustPinPluginProps> = (config, props) =>
  withAppDelegate(config, modConfig => {
    if (modConfig.modResults.language !== 'swift') {
      throw new TrustPinPluginError(
        `expected a Swift AppDelegate, found "${modConfig.modResults.language}". ` +
          'Add [TrustPinReactNative startWithLogLevelName:nil] manually before the React Native setup.',
      );
    }
    modConfig.modResults.contents = addStartCall(modConfig.modResults.contents, props.logLevel);
    return modConfig;
  });

export const withTrustPinIos: ConfigPlugin<TrustPinPluginProps> = (config, props) => {
  let next = withTrustPinPlist(config, props);
  next = withPlistInBundle(next);
  next = withEmbeddedSeed(next, props);
  next = withEmbeddedSeedInBundle(next, props);
  return withInitCall(next, props);
};
